# Generated by Django 3.0.3 on 2020-09-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0012_auto_20200422_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='150 words max', max_length=150)),
                ('img_link', models.CharField(default='500 words link max', max_length=500)),
                ('summary', models.TextField(default='500 words max', max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
