# Generated by Django 3.0.3 on 2020-09-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0013_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='myside',
            field=models.CharField(default='badge', max_length=50),
        ),
    ]
